Config jenkinsfile

diff --git a/ci/Jenkinsfile b/ci/Jenkinsfile
--- a/ci/Jenkinsfile
+++ b/ci/Jenkinsfile
@@ -32,6 +32,8 @@ pipeline {
                     do
                         cd spring-petclinic-${SERVICE}
                         mvn clean package -DskipTests
+                        echo "Contents of target directory for ${SERVICE}:"
+                        ls -l target
                         if [ ! -f target/*.jar ]; then
                             echo "Error: JAR file not found for ${SERVICE}"
                             exit 1
@@ -61,6 +63,10 @@ pipeline {
                                 echo "Building image: ${imageName}"
 
                                 sh """
+                                    if [ ! -f ${serviceDir}/target/*.jar ]; then
+                                        echo "Error: JAR file not found in ${serviceDir}/target"
+                                        exit 1
+                                    fi
                                     mv ${serviceDir}/target/*.jar ${serviceDir}/target/app.jar
                                     docker build -t ${imageName} -f ${serviceDir}/Dockerfile ${serviceDir}
                                     docker tag ${imageName} ${DOCKERHUB_USER}/spring-petclinic-${SERVICE}:latest
